const actionTypes = Object.freeze({
	//app startup
	APP_START_UP_COMPLETE: "APP_START_UP_COMPLETE",
	SET_CONTENT_OF_CONFIRM_MODAL: "SET_CONTENT_OF_CONFIRM_MODAL",
	CHANGE_LANGUAGE: "CHANGE_lANGUAGE",

	//system
	SUCCESSFULLY_AUTHENTICATE: "SUCCESSFULLY_AUTHENTICATE",
	UN_SUCCESSFULLY_AUTHENTICATE: "UNSUCCESSFULLY_AUTHENTICATE",

	//admin
});

export default actionTypes;
